export { default as UploadIcon } from './UploadIcon'
export { default as CheckIcon } from './CheckIcon'
export { default as BackIcon } from './BackIcon'
export { default as DownIcon } from './DownIcon'
export { default as QuestionIcon } from './QuestionIcon'
